apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ print .Values.hostname "-vs" | replace "." "-" }}
spec:
  hosts:
  - {{ .Values.hostname  }}
  gateways:
  -  {{ .Values.istio_gateway }}
  http:
  - match:
    - uri:
        prefix: "/api"
    route:
    - destination:
        host: {{ print .Values.app_name "-api-svc" }}
        port:
          number: 5000
  - route:
    - destination:
        host: {{ print .Values.app_name "-spa-svc" }}
        port:
          number: 80

  