---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Values.app_name "-api-svc" }}
  labels:
    version: "1.0"
spec:
  selector:
    app: {{ .Values.app_name "-api" }}
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Values.app_name "-spa-svc" }}
  labels:
    version: "1.0"
spec:
  selector:
    app: {{ .Values.app_name "-spa" }}
  ports:
  - port: 80  
    targetPort: 80
  type: ClusterIP
