---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Values.app_name "-svc" }}
  labels:
    version: "1.0"
spec:
  selector:
    app: {{ .Values.app_name }}
  ports:
  - port: 3000  
    targetPort: 3000
  type: ClusterIP
