apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: aad-b2c-tenant
spec:
  hosts:
  - {{ .Values.b2c_tenanat  }}
  - login.microsoftonline.com
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL