apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ print .Values.app_name "-api" }}
spec:
  selector:
    matchLabels:
      app: {{ print .Values.app_name "-api" }}
      lang: nodejs
  replicas: {{ .Values.replicas }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ print .Values.app_name "-api"}}
        lang: nodejs
    spec:
      containers:
      - name: todoapi
        image: {{ print .Values.todo_api_image ":" .Values.todo_build_version | nospace  }} 
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ print .Values.app_name "-spa" }}
spec:
  selector:
    matchLabels:
      app: {{ print .Values.app_name "-spa" }}
      lang: nodejs
  replicas: {{ .Values.replicas }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ print .Values.app_name "-spa" }}
        lang: nodejs
    spec:
      containers:
      - name: todospa
        image: {{ print .Values.todo_spa_image ":" .Values.todo_build_version | nospace  }} 
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"