#FROM node:10-alpine as build
FROM node:lts-alpine3.17 as build

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY package.json .
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "npm", "start" ]

#RUN npm run build
#
#FROM nginx:stable-alpine
#COPY --from=build /home/node/app/build /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
